version: '3'
services: 
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code/web
    environment:
      - NODE_ENV=development
    command: npm run dev
  api:
    build: ./api/
    ports:
      - "8765:8765"
    volumes:
      - ./api:/code/api