version: '3'
services: 
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code/web
    environment:
      - NODE_ENV=development
    command: npm run dev
  server:
    build: ./server/
    ports:
      - "8765:8765"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/vehicle_data
    volumes:
      - ./server:/code/server
  mongodb:
    build: ./database/
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb_data:/data/db

